from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument
from launch.substitutions import LaunchConfiguration, PathJoinSubstitution
from launch_ros.actions import Node
from launch_ros.substitutions import FindPackageShare


def generate_launch_description():
    default_config = PathJoinSubstitution([FindPackageShare("turtlebot3_drl_local_planner"), "config", "gap_sac.yaml"])
    return LaunchDescription(
        [
            DeclareLaunchArgument("config_file", default_value=default_config),
            DeclareLaunchArgument("policy_checkpoint", default_value=""),
            DeclareLaunchArgument("input_goal_topic", default_value="/goal_pose"),
            DeclareLaunchArgument("input_plan_topic", default_value="/plan"),
            DeclareLaunchArgument("output_cmd_vel_topic", default_value="/cmd_vel_drl"),
            DeclareLaunchArgument("publish_directly_to_cmd_vel", default_value="false"),
            DeclareLaunchArgument("safety_stop_enabled", default_value="true"),
            DeclareLaunchArgument("safety_stop_distance", default_value="0.18"),
            DeclareLaunchArgument("plan_target_mode", default_value="lookahead"),
            DeclareLaunchArgument("lookahead_distance_m", default_value="0.6"),
            DeclareLaunchArgument("prefer_plan_goal", default_value="true"),
            DeclareLaunchArgument("publish_debug", default_value="true"),
            DeclareLaunchArgument("heading_guard_enabled", default_value="true"),
            DeclareLaunchArgument("heading_guard_min_heading_rad", default_value="0.08"),
            DeclareLaunchArgument("heading_guard_gain", default_value="1.2"),
            DeclareLaunchArgument("heading_guard_clearance_m", default_value="0.30"),
            DeclareLaunchArgument("goal_stop_distance_m", default_value="0.35"),
            DeclareLaunchArgument("speed_governor_enabled", default_value="true"),
            DeclareLaunchArgument("speed_slow_distance_m", default_value="0.45"),
            DeclareLaunchArgument("speed_min_distance_m", default_value="0.22"),
            DeclareLaunchArgument("speed_min_scale", default_value="0.15"),
            DeclareLaunchArgument("recovery_enabled", default_value="true"),
            DeclareLaunchArgument("recovery_linear_velocity", default_value="-0.035"),
            DeclareLaunchArgument("recovery_angular_velocity", default_value="0.55"),
            DeclareLaunchArgument("recovery_front_angle_rad", default_value="0.35"),
            DeclareLaunchArgument("recovery_duration_sec", default_value="0.8"),
            DeclareLaunchArgument("narrow_passage_enabled", default_value="true"),
            DeclareLaunchArgument("narrow_passage_clearance_m", default_value="0.42"),
            DeclareLaunchArgument("narrow_passage_front_clearance_m", default_value="0.24"),
            DeclareLaunchArgument("narrow_passage_linear_velocity", default_value="0.025"),
            DeclareLaunchArgument("narrow_passage_centering_gain", default_value="1.4"),
            DeclareLaunchArgument("narrow_passage_max_angular_velocity", default_value="0.45"),
            DeclareLaunchArgument("use_fixed_goal_when_missing", default_value="false"),
            DeclareLaunchArgument("fixed_goal_x", default_value="-1.0"),
            DeclareLaunchArgument("fixed_goal_y", default_value="-0.2"),
            DeclareLaunchArgument("fixed_goal_yaw", default_value="0.0"),
            Node(
                package="turtlebot3_drl_local_planner",
                executable="drl_controller_node",
                name="drl_controller_node",
                output="screen",
                parameters=[
                    {
                        "config_file": LaunchConfiguration("config_file"),
                        "policy_checkpoint": LaunchConfiguration("policy_checkpoint"),
                        "input_goal_topic": LaunchConfiguration("input_goal_topic"),
                        "input_plan_topic": LaunchConfiguration("input_plan_topic"),
                        "output_cmd_vel_topic": LaunchConfiguration("output_cmd_vel_topic"),
                        "publish_directly_to_cmd_vel": LaunchConfiguration("publish_directly_to_cmd_vel"),
                        "safety_stop_enabled": LaunchConfiguration("safety_stop_enabled"),
                        "safety_stop_distance": LaunchConfiguration("safety_stop_distance"),
                        "plan_target_mode": LaunchConfiguration("plan_target_mode"),
                        "lookahead_distance_m": LaunchConfiguration("lookahead_distance_m"),
                        "prefer_plan_goal": LaunchConfiguration("prefer_plan_goal"),
                        "publish_debug": LaunchConfiguration("publish_debug"),
                        "heading_guard_enabled": LaunchConfiguration("heading_guard_enabled"),
                        "heading_guard_min_heading_rad": LaunchConfiguration("heading_guard_min_heading_rad"),
                        "heading_guard_gain": LaunchConfiguration("heading_guard_gain"),
                        "heading_guard_clearance_m": LaunchConfiguration("heading_guard_clearance_m"),
                        "goal_stop_distance_m": LaunchConfiguration("goal_stop_distance_m"),
                        "speed_governor_enabled": LaunchConfiguration("speed_governor_enabled"),
                        "speed_slow_distance_m": LaunchConfiguration("speed_slow_distance_m"),
                        "speed_min_distance_m": LaunchConfiguration("speed_min_distance_m"),
                        "speed_min_scale": LaunchConfiguration("speed_min_scale"),
                        "recovery_enabled": LaunchConfiguration("recovery_enabled"),
                        "recovery_linear_velocity": LaunchConfiguration("recovery_linear_velocity"),
                        "recovery_angular_velocity": LaunchConfiguration("recovery_angular_velocity"),
                        "recovery_front_angle_rad": LaunchConfiguration("recovery_front_angle_rad"),
                        "recovery_duration_sec": LaunchConfiguration("recovery_duration_sec"),
                        "narrow_passage_enabled": LaunchConfiguration("narrow_passage_enabled"),
                        "narrow_passage_clearance_m": LaunchConfiguration("narrow_passage_clearance_m"),
                        "narrow_passage_front_clearance_m": LaunchConfiguration("narrow_passage_front_clearance_m"),
                        "narrow_passage_linear_velocity": LaunchConfiguration("narrow_passage_linear_velocity"),
                        "narrow_passage_centering_gain": LaunchConfiguration("narrow_passage_centering_gain"),
                        "narrow_passage_max_angular_velocity": LaunchConfiguration("narrow_passage_max_angular_velocity"),
                        "use_fixed_goal_when_missing": LaunchConfiguration("use_fixed_goal_when_missing"),
                        "fixed_goal_x": LaunchConfiguration("fixed_goal_x"),
                        "fixed_goal_y": LaunchConfiguration("fixed_goal_y"),
                        "fixed_goal_yaw": LaunchConfiguration("fixed_goal_yaw"),
                    }
                ],
            ),
        ]
    )
