<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>turtlebot3_opentcs_simulations</name>
  <version>0.0.0</version>
  <description>
    OpenTCS integration with TurtleBot3 in simulations
  </description>
  <maintainer email="todo@example.com">TODO</maintainer>
  <license>Apache 2.0</license>
  <buildtool_depend>ament_python</buildtool_depend>
</package>
